import './globals.css'
import type { Metadata } from 'next'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'next-application',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="night">
      <body className="min-h-screen flex flex-col">
        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  )
}
